language: python
python:
  - "2.7.15"
  - "3.6.7"
cache: pip
dist: xenial
# for fast build I used only py 2.7 and 3.6
# command to install dependencies
install:
  - pip install -r tests/requirements.txt
# command to run tests
script:
  - pytest -vs
